// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwKjF3XQKvU8-pLdM5JkRrrpy9hxpOwkY',
    appId: '1:105604883550:web:f3901e88a8b19d7ec400cf',
    messagingSenderId: '105604883550',
    projectId: 'tromega-21238',
    authDomain: 'tromega-21238.firebaseapp.com',
    storageBucket: 'tromega-21238.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLyKVtVh0ej4VVsL7YvjSJV7io-KQdvi0',
    appId: '1:105604883550:android:4a86afd74037b63ac400cf',
    messagingSenderId: '105604883550',
    projectId: 'tromega-21238',
    storageBucket: 'tromega-21238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqwaP6TBIhO_tsO7_Gn8U7nIoDYMtS9Z8',
    appId: '1:105604883550:ios:4de61f00a814aafcc400cf',
    messagingSenderId: '105604883550',
    projectId: 'tromega-21238',
    storageBucket: 'tromega-21238.appspot.com',
    iosClientId: '105604883550-ebnip0q2uj6mpcpm633hpamkftrjigm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tromega',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqwaP6TBIhO_tsO7_Gn8U7nIoDYMtS9Z8',
    appId: '1:105604883550:ios:4de61f00a814aafcc400cf',
    messagingSenderId: '105604883550',
    projectId: 'tromega-21238',
    storageBucket: 'tromega-21238.appspot.com',
    iosClientId: '105604883550-ebnip0q2uj6mpcpm633hpamkftrjigm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tromega',
  );
}
